image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

# Before Script
before_script:
  - . sh/npm-install.sh
  - . sh/check-version.sh

test:
  stage: test
  script:
    - echo "test"
  only:
    - dev
    - test

build:
  stage: build
  dependencies:
    - test
  script:
    - echo "build"
  artifacts:
    paths:
      - build
  only:
    - dev
    - master

pages:
  stage: deploy
  dependencies:
    - test
    - build
  script:
    - mv build/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - dev
    - master
