# Travics Cheatsheet : https://devhints.io/travis
language: node_js

node_js: lts/*

install: true

before_script:
  - . sh/npm-install.sh
  - . sh/check-version.sh

script:
  - echo "script"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: build
  on:
    branch: master
